excluded: # paths to ignore during linting
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  
disabled_rules: # rule identifiers turned on by default to exclude from running
  - multiple_closures_with_trailing_closure

force_cast: warning # implicitly. Give warning only for force casting
force_try:
  severity: warning # explicitly. Give warning only for force try

line_length:
  warning: 120
  error: 200
  #ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

function_parameter_count:
  warning: 5
  error: 15

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 400
  error: 800

type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50

identifier_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

opt_in_rules:
  - force_unwrapping
  - let_var_whitespace
  - trailing_whitespace











